I'm sorry, but an uncaught exception occurred.

While executing init code:
  File "game/script.rpy", line 62, in script
    image doge doge = anim.Blink(Image(im.Scale("images/doge.jpeg"), 250, 250))
  File "game/script.rpy", line 62, in <module>
    image doge doge = anim.Blink(Image(im.Scale("images/doge.jpeg"), 250, 250))
TypeError: __init__() takes at least 4 arguments (2 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 62, in script
    image doge doge = anim.Blink(Image(im.Scale("images/doge.jpeg"), 250, 250))
  File "C:\Users\Rovic\Desktop\@ renpy-6.17.7-sdk\renpy\ast.py", line 846, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\Rovic\Desktop\@ renpy-6.17.7-sdk\renpy\python.py", line 1406, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 62, in <module>
    image doge doge = anim.Blink(Image(im.Scale("images/doge.jpeg"), 250, 250))
TypeError: __init__() takes at least 4 arguments (2 given)

Windows-7-6.1.7600
Ren'Py 6.17.7.521
Project Sweeegggg 4.0
